# Generated by Django 2.2.2 on 2019-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
